Liquid::Template.register_tag('attributerow', AttributeRow)
Liquid::Template.register_tag('nestedproductrow', NestedProductRow)
Liquid::Template.register_tag('roomrow', RoomRow)
Liquid::Template.register_tag('statusrow', StatusRow)
Liquid::Template.register_tag('now', Now)